### Numpy Indexing and Selection

In [1]:
import numpy as np

In [25]:
arr = np.arange(25)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

### Bracket Indexing and Selection

In [6]:
arr[1: 5]

array([1, 2, 3, 4])

In [7]:
arr[0: 5]

array([0, 1, 2, 3, 4])

In [9]:
arr[4:]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24])

In [11]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [13]:
arr[1:6:2]

array([1, 3, 5])

In [15]:
arr[-1]

24

In [16]:
arr[::-1]

array([24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,
        7,  6,  5,  4,  3,  2,  1,  0])

In [35]:
arr[10:3:-2]

array([10,  8,  6,  4])

In [36]:
arr[3:10:-2]# does not exist

array([], dtype=int32)

### Broadcasting

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [39]:
arr[0:5] = 100

In [40]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [42]:
arr = np.arange(0, 11)

In [45]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
slice_of_arr = arr[0:6]

In [52]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [54]:
slice_of_arr[:] = 99

In [55]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [56]:
arr_copy = arr.copy()

In [57]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [59]:
slice_of_arr[:] = 100

In [61]:
slice_of_arr

array([100, 100, 100, 100, 100, 100])

In [63]:
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [65]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

# Indexing a 2D array (matrices) 

In [69]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30],[35, 40, 35]])

In [70]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 35]])

In [73]:
arr_2d[1]

array([20, 25, 30])

In [76]:
arr_2d[1][0]

20

In [77]:
arr_2d[1, 0] # it's equal to previous one

20

In [80]:
arr_2d[0:2,1:]

array([[10, 15],
       [25, 30]])

In [83]:
arr_2d[:, 2:]

array([[15],
       [30],
       [35]])

# Fancy Indexing 

In [94]:
arr2d = np.zeros((10,10))

In [93]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [96]:
arr2d.shape[0] # size of first row

10

In [98]:
sz = arr2d.shape[0] 

In [99]:
for i in range(sz):
    for j in range(sz):
        arr2d[i][j] = i

In [102]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [104]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [105]:
x = np.arange(1,50).reshape(7,7)

In [107]:
x

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49]])

In [109]:
x[1:4, 3: -1]

array([[11, 12, 13],
       [18, 19, 20],
       [25, 26, 27]])

In [116]:
x[[1,3,5], 3:-1]

array([[11, 12, 13],
       [25, 26, 27],
       [39, 40, 41]])

In [118]:
x[1:6:2, 3: -1]

array([[11, 12, 13],
       [25, 26, 27],
       [39, 40, 41]])

### Selection

In [121]:
arr = np.arange(1,11)

In [124]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [125]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [127]:
x = arr > 4

In [128]:
arr[x]

array([ 5,  6,  7,  8,  9, 10])

In [129]:
arr[arr > 4] # same as previous one

array([ 5,  6,  7,  8,  9, 10])

In [136]:
arr[(arr != 4) & (arr < 5)]

array([1, 2, 3])

In [137]:
(arr!=4) & (arr< 5)

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [140]:
arr[(arr != 4) | (arr > 5)]

array([ 1,  2,  3,  5,  6,  7,  8,  9, 10])